server:
  port: 9092
spring:
  application:
    name: "User Resource"
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: '123456'
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8