server:
  port: 11111

spring:
  rabbitmq:
    host: http://192.168.56.101:15672
    username: "user"
    password: "123456"
#    listener:
#      simple:
#        # ack 手动答交
#        acknowledge-mode: none